development:
  paypal_email: seller_1343207727_biz@axat-tech.com
  paypal_secret: foobar
  paypal_cert_id: UW7T4YNMGMBT2
  paypal_url: "https://www.sandbox.paypal.com/cgi-bin/webscr"

test:
  paypal_email: test@example.com
  paypal_secret: testsecret
  paypal_cert_id: 123456789
  paypal_url: testpaypalurl

production:
  paypal_email: seller_1343207727_biz@axat-tech.com
  paypal_secret: foobar
  paypal_cert_id: UW7T4YNMGMBT2
  paypal_url: "https://www.sandbox.paypal.com/cgi-bin/webscr"

